### ISSUE TITLE
NixOS packaging

### ISSUE THREAD

**Issue by Aras14HD** [isledecomp/isle-portable#414]
I made a package for Nix, but there are still a few questions, that should be answered.
- [x] Due to you using the git version of SDL3 and not the release, I had to make a minor patch. SDL_SCALEMODE_PIXELART is not available, for now I replaced it with SDL_SCALEMODE_NEAREST. Is there a better option, or is the git version necessary?
- [x] You do not yet have versioning, should I just use the short commit hash?
- [x] Do you have special wishes for package naming and description (both short and long)?
- [x] What is the licensing situation, is it proprietary?

I can't guarantee that I'll be updating the package very often (likely just weekly) and I can't guarantee that it'll ever be on nixpkgs, but I will try to do my best.

<details>
<summary>the code (preliminary and unpublished)</summary>

```nix
{
  stdenv,
  fetchgit,
  pkg-config,
  cmake,
  lib,
  sdl3,
  iniparser,
  python311,
  glew,
  qt6,
}:

stdenv.mkDerivation {
  pname = "isle-portable";
  version = "1.0.0";

  src = fetchgit {
    url = "https://github.com/isledecomp/isle-portable.git";
    rev = "0c66273c9fc65ef2df598b1f20ab16a2d01e0258";
    sha256 = "sha256-P2wpzV+SHhEuA1LWsbWPMjYCSsmTrbSrb7N1IKWAHpQ=";
    fetchSubmodules = true;
  };

  nativeBuildInputs = [
    pkg-config
    cmake
  ];

  buildInputs = [ sdl3 iniparser python311 glew qt6.qtbase qt6.wrapQtAppsHook ];

  preConfigure = ''
    cmakeFlagsArray+=(
      "-DDOWNLOAD_DEPENDENCIES=OFF"
    )
  '';
  

  meta = with lib; {
    description = "A protable Lego Island decomp";
    longDescription = ''
        The portable version allows running Lego Island natively
    '';

    homepage = "https://github.com/isledecomp/isle-portable";

    license = licenses.unfree;

    mainProgram = "isle";

    maintainers = with maintainers; [ ];
    platforms = platforms.linux;
  };

}
```
</details>

**Comment by Aras14HD** [comment]
Ah just saw that you fixed the SDL_SCALEMODE_PIXELART issue. Is resolved.

**Comment by Aras14HD** [comment]
Ok, since it is still in a dev state, I'd only keep it in a repo and make it accessible through that. So versioning is a non-issue, for the rest, while not truly important, would be nice to know.

**Comment by AJenbo** [comment]
isn't this a duplicate of https://github.com/isledecomp/isle-portable/issues/366.

The license is 77% lgpl

current version appears to be 0.1 but isn't fixed to a specific commit

**Comment by Aras14HD** [comment]
Sorry, maybe should have just made a comment there... (though most stuff there is not applicable to nix) Thanks for the info!

Have put the current state here: https://github.com/Aras14HD/isle-portable-nix (usable as a flake with `nix build github:Aras14HD/isle-portable-nix`)

It seems to be working well right now. And I think that would be everything. Thanks again for working on such an amazing project!

**Comment by RossSmyth** [comment]
https://github.com/NixOS/nixpkgs/pull/419421
